/**
 * decision.test.ts — validateThesisDecision(), the V2 writer's in-loop
 * Layer-1 pre-validation. These rules are what turns a would-be persist
 * rejection into a one-step repair inside the research loop, so the
 * accept/reject boundary is pinned hard.
 */

import {
  thesisDecisionSchema,
  validateThesisDecision,
  type ThesisDecisionInput,
} from "./decision";
import { editTriggerOpSchema } from "@/lib/agent/triggers/schema";

const validLong: ThesisDecisionInput = {
  direction: "LONG",
  rationale: "Blackwell ramp is underpriced; entry at the breakout with a clean 2.5:1.",
  horizon: "TARGET",
  entry_price: 100,
  target_price: 125,
  stop_loss: 90,
  core_belief:
    "NVDA prints ≥$50B data-center revenue by Q4 FY26 as Blackwell replaces Hopper at hyperscalers.",
  key_assumptions: ["DC capex stays above $200B/yr", "Blackwell yields hold above 60%"],
  invalidation_conditions: ["Gross margin below 70% on next print", "Guidance cut on DC revenue"],
  scoring: {
    trendStrength: { score: 3, note: "multi-week uptrend, rising 50d" },
    relativeStrength: { score: 2, note: "+28% YTD vs AMD +14%" },
    entryQuality: { score: 2, note: "pullback to 20d in trend" },
    catalystFreshness: { score: 2, note: "earnings 3 weeks out, beat-raise setup" },
  },
  conviction: "HIGH",
  conviction_rationale:
    "I really like this setup — the catalyst is ahead and consensus is too conservative on DC revenue.",
  variant_view: "Consensus models $42B DC; channel checks support $50B+ — 2 quarters underweighted.",
};

const mintOpts = { mode: "mint" as const, existingStatus: null, currentPrice: 101 };

describe("validateThesisDecision — accept paths", () => {
  it("accepts a fully-specified LONG mint and computes composite + R/R", () => {
    const v = validateThesisDecision(validLong, mintOpts);
    expect(v.ok).toBe(true);
    expect(v.errors).toEqual([]);
    expect(v.decision?.composite).toBe(9);
    expect(v.riskReward).toBeCloseTo(2.5);
  });

  it("accepts a PASS with only rationale + horizon (no prices, no conviction)", () => {
    const v = validateThesisDecision(
      {
        direction: "PASS",
        rationale: "No 2:1 setup at current prices; revisit below the 50d around $85.",
        horizon: "TARGET",
      },
      mintOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("accepts a valid SHORT with mirrored price ordering", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        direction: "SHORT",
        entry_price: 100,
        target_price: 80,
        stop_loss: 108,
      },
      mintOpts,
    );
    expect(v.ok).toBe(true);
    expect(v.riskReward).toBeCloseTo(2.5);
  });

  it("accepts omitted triggers (horizon defaults apply downstream)", () => {
    const v = validateThesisDecision({ ...validLong, triggers: undefined }, mintOpts);
    expect(v.ok).toBe(true);
    expect(v.decision?.triggers).toBeUndefined();
  });

  it("accepts a well-formed WATCHING trigger ladder (ENTER + REVIEW)", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        triggers: [
          {
            predicate: { kind: "PRICE_ABOVE", level: 100 },
            action: "ENTER",
            rationale: "breakout entry",
          },
          {
            predicate: { kind: "EARNINGS_MISS", minSurprisePct: 3 },
            action: "REVIEW",
            rationale: "guidance miss kills the thesis",
          },
        ],
      },
      mintOpts,
    );
    expect(v.ok).toBe(true);
    expect(v.decision?.triggers).toHaveLength(2);
    // ids are auto-generated by the schema default
    expect(v.decision?.triggers?.[0].id).toBeTruthy();
  });
});

describe("validateThesisDecision — R/R floor and price ordering", () => {
  it("rejects a LONG below 2:1", () => {
    const v = validateThesisDecision(
      { ...validLong, target_price: 115, stop_loss: 90 }, // 15/10 = 1.5
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("R/R floor");
  });

  it("rejects inverted LONG ordering (stop above entry)", () => {
    const v = validateThesisDecision(
      { ...validLong, stop_loss: 105 },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("price ordering");
  });

  it("rejects a half-priced plan (target + stop, no entry)", () => {
    const v = validateThesisDecision(
      { ...validLong, entry_price: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("entry_price");
  });
});

describe("validateThesisDecision — a view with no entry yet (unpriced LONG/SHORT)", () => {
  const unpriced: ThesisDecisionInput = {
    ...validLong,
    entry_price: undefined,
    target_price: undefined,
    stop_loss: undefined,
    rationale: "Bullish into the January readout; entry to be priced after the data. Not a PASS.",
  };

  it("mint: accepted with no levels and no triggers (horizon defaults supply the wakes)", () => {
    const v = validateThesisDecision(unpriced, mintOpts);
    expect(v.ok).toBe(true);
    expect(v.riskReward).toBeUndefined();
  });

  it("refresh on a priced row: omitting the levels AND the triggers is refused — the plan would silently stay", () => {
    const v = validateThesisDecision(unpriced, {
      mode: "refresh",
      existingStatus: "WATCHING",
      currentPrice: 101,
      existingTargetPrice: 130,
    });
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("remove_trigger_ids");
  });

  it("refresh on a priced row: removing the plan triggers (and keeping a REVIEW wake) is accepted", () => {
    // FLIPPED 2026-09-09 (DAV-242): the set-down is ops by id, not a resent list.
    const v = validateThesisDecision(
      {
        ...unpriced,
        remove_trigger_ids: ["buy", "floor", "target"],
        add_triggers: [
          { predicate: { kind: "REVIEW_CADENCE", days: 120 }, action: "REVIEW", rationale: "Price it after the January readout." },
        ],
      },
      { mode: "refresh", existingStatus: "WATCHING", currentPrice: 101, existingTargetPrice: 130 },
    );
    expect(v.ok).toBe(true);
    expect(v.decision?.add_triggers).toHaveLength(1);
  });
});

describe("validateThesisDecision — belief + conviction requirements (LONG/SHORT)", () => {
  it("rejects missing core_belief / thin assumptions / thin invalidations", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        core_belief: undefined,
        key_assumptions: ["only one"],
        invalidation_conditions: [],
      },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    const all = v.errors.join(" ");
    expect(all).toContain("core_belief");
    expect(all).toContain("key_assumptions");
    expect(all).toContain("invalidation_conditions");
  });

  it("rejects STRONG/HIGH conviction without a variant view", () => {
    const v = validateThesisDecision(
      { ...validLong, conviction: "STRONG", variant_view: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("variant_view");
  });

  it("allows MEDIUM conviction without a variant view", () => {
    const v = validateThesisDecision(
      { ...validLong, conviction: "MEDIUM", variant_view: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("rejects missing scoring dimensions and out-of-cap scores", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        scoring: {
          trendStrength: { score: 5, note: "over cap" },
          relativeStrength: { score: 2, note: "ok" },
          entryQuality: { score: 2, note: "" },
          catalystFreshness: { score: 2, note: "ok" },
        },
      },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    const all = v.errors.join(" ");
    expect(all).toContain("scoring.trendStrength");
    expect(all).toContain("scoring.entryQuality");
  });
});

describe("validateThesisDecision — horizon conditionals", () => {
  it("CATALYST requires catalyst_date", () => {
    const v = validateThesisDecision(
      { ...validLong, horizon: "CATALYST", catalyst_date: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("catalyst_date");
  });

  it("no longer requires max_hold_days on a TRADE", () => {
    // The column is gone (DAV-195 L8). "This has been open long enough" is a
    // review cadence the TRADE template mints — on the ladder,
    // where it can be seen and edited, instead of a field that fed a
    // template once at mint and then drifted from it.
    const v = validateThesisDecision(
      { ...validLong, horizon: "TRADE" },
      mintOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("rejects an unparseable catalyst_date", () => {
    const v = validateThesisDecision(
      { ...validLong, horizon: "CATALYST", catalyst_date: "next month sometime" },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("not a parseable date");
  });
});

describe("validateThesisDecision — trigger action-set by position state", () => {
  const enterTrigger = {
    predicate: { kind: "PRICE_ABOVE", level: 100 },
    action: "ENTER",
    rationale: "breakout",
  };
  const exitTrigger = {
    predicate: { kind: "PRICE_BELOW", level: 90 },
    action: "EXIT",
    rationale: "stop",
  };

  it("mint (no position): EXIT/TRIM/ADD/MOVE_STOP are forbidden", () => {
    const v = validateThesisDecision({ ...validLong, triggers: [exitTrigger] }, mintOpts);
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("no position exists");
  });

  // On a refresh the same rules run on `add_triggers` (DAV-242: a refresh
  // edits one trigger at a time; `triggers` is a mint-only argument).
  it("HOLDING refresh: adding an ENTER is forbidden", () => {
    const v = validateThesisDecision(
      { ...validLong, add_triggers: [enterTrigger] },
      { mode: "refresh", existingStatus: "HOLDING", currentPrice: 101 },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("ENTER triggers are forbidden");
  });

  it("HOLDING refresh: adding EXIT + REVIEW is legal", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        add_triggers: [
          exitTrigger,
          {
            predicate: { kind: "REVIEW_CADENCE", days: 7 },
            action: "REVIEW",
            rationale: "scheduled hygiene",
          },
        ],
      },
      { mode: "refresh", existingStatus: "HOLDING", currentPrice: 101 },
    );
    expect(v.ok).toBe(true);
  });

  it("PROMOTED refresh (no live position): adding EXIT is forbidden, ENTER is legal", () => {
    const promotedOpts = { mode: "refresh" as const, existingStatus: "PROMOTED", currentPrice: 101 };
    expect(
      validateThesisDecision({ ...validLong, add_triggers: [exitTrigger] }, promotedOpts).ok,
    ).toBe(false);
    expect(
      validateThesisDecision({ ...validLong, add_triggers: [enterTrigger] }, promotedOpts).ok,
    ).toBe(true);
  });

  it("refresh: a whole `triggers` list is refused — edit one at a time", () => {
    const v = validateThesisDecision(
      { ...validLong, triggers: [exitTrigger] },
      { mode: "refresh", existingStatus: "HOLDING", currentPrice: 101 },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("one at a time");
  });

  it("refresh: a level edit without a rationale is refused in the loop", () => {
    const v = validateThesisDecision(
      { ...validLong, edit_triggers: [{ id: "floor", level: 95 }] },
      { mode: "refresh", existingStatus: "HOLDING", currentPrice: 101 },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("requires a rationale");
  });

  it("mint: ops are refused — there is nothing to edit yet", () => {
    const v = validateThesisDecision({ ...validLong, remove_trigger_ids: ["x"] }, mintOpts);
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("a mint has no existing triggers");
  });

  it("malformed trigger shapes are reported as repairable errors, not thrown", () => {
    const v = validateThesisDecision(
      { ...validLong, triggers: [{ nonsense: true }] },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("triggers: invalid shape");
    expect(v.errors.join(" ")).toContain("OMIT the triggers field");
  });
});

describe("validateThesisDecision — persist-gate mirrors (review finding #4)", () => {
  it("rejects a PASS carrying triggers", () => {
    const v = validateThesisDecision(
      {
        direction: "PASS",
        rationale: "No edge at current prices; keep an eye on the reclaim level.",
        horizon: "TARGET",
        triggers: [
          { predicate: { kind: "PRICE_ABOVE", level: 100 }, action: "ENTER", rationale: "x" },
        ],
      },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("PASS decision cannot carry triggers");
  });

  it("goalpost mirror: rejects a target raise on WATCHING when price already crossed the old target", () => {
    const v = validateThesisDecision(
      { ...validLong, target_price: 140 },
      {
        mode: "refresh",
        existingStatus: "WATCHING",
        currentPrice: 132,
        existingTargetPrice: 130,
      },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("goalpost");
  });

  it("goalpost mirror: allows a target raise while price is still below the old target", () => {
    const v = validateThesisDecision(
      { ...validLong, target_price: 140, stop_loss: 84 },
      {
        mode: "refresh",
        existingStatus: "WATCHING",
        currentPrice: 101,
        existingTargetPrice: 130,
      },
    );
    expect(v.ok).toBe(true);
  });

  it("a refresh on a thesis with no triggers may omit triggers — zero is legal (DAV-209)", () => {
    const v = validateThesisDecision({ ...validLong, triggers: undefined }, {
      mode: "refresh",
      existingStatus: "WATCHING",
      currentPrice: 101,
      existingTargetPrice: 130,
    });
    expect(v.ok).toBe(true);
  });

  it("refresh: adding a REVIEW wake on a watch is accepted — the buy trigger already on the row is not being replaced", () => {
    // FLIPPED 2026-09-09 (DAV-242): the "ladder must carry an ENTER / EXIT"
    // mirrors existed because a resent list replaced the whole ladder. An
    // op adds one trigger; the buy and sell triggers on the row stay, and
    // the tool checks the resulting plan once at persist.
    const v = validateThesisDecision(
      {
        ...validLong,
        add_triggers: [
          { predicate: { kind: "REVIEW_CADENCE", days: 7 }, action: "REVIEW", rationale: "hygiene" },
        ],
      },
      { mode: "refresh", existingStatus: "WATCHING", currentPrice: 90, existingTargetPrice: 130 },
    );
    expect(v.ok).toBe(true);
  });
});

describe("validateThesisDecision — P1-35 prior-exit acknowledgment mirror", () => {
  const soldOpts = {
    ...mintOpts,
    priorExit: { exitPrice: 95, daysAgo: 3, closeReason: "STOP" },
  };

  it("requires the acknowledgment when entry is at/above a ≤14d exit", () => {
    // validLong entry 100 ≥ exit 95.
    const v = validateThesisDecision(validLong, soldOpts);
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("prior_exit_acknowledgment");
  });

  it("accepts with a genuine acknowledgment", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        prior_exit_acknowledgment:
          "Stopped out at $95 on the trail; re-entering only above the reclaimed breakout at $100 — new structure, not a dip re-buy.",
      },
      soldOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("no acknowledgment needed below the exit price", () => {
    const v = validateThesisDecision(
      { ...validLong, entry_price: 90, target_price: 115, stop_loss: 84 },
      soldOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("PASS decisions skip the gate (institutional memory is welcome)", () => {
    const v = validateThesisDecision(
      { direction: "PASS", rationale: "Sold it three days ago; nothing has changed since the exit.", horizon: "TARGET" },
      soldOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("refresh mode never requires the ack (gate is mint-only)", () => {
    const v = validateThesisDecision(validLong, {
      mode: "refresh",
      existingStatus: "WATCHING",
      currentPrice: 101,
      existingTargetPrice: 130,
      priorExit: { exitPrice: 95, daysAgo: 3, closeReason: "STOP" },
    });
    expect(v.ok).toBe(true);
  });
});

// ─── DAV-257: one edit form for the writer and the save ─────────────────────
// PRAX 2026-09-11: the writer put the review cadence's wording into
// edit_triggers[0].action. submit_thesis accepted it (its copy of the form had
// action: string), update_thesis refused it at save (the enum), and the whole
// paid refresh was thrown away — the save has no retry, the submit loop does.

describe("submit_thesis edit_triggers — the same form update_thesis saves (DAV-257)", () => {
  const PRAX_0911_EDIT = {
    id: "3998148e-9487-4d0a-9dca-99b71178e1a9",
    action:
      "Weekly PDUFA-path check-in — monitor for any new FDA correspondence, BIMO outcomes, or analyst updates ahead of the December 27 relutrigine PDUFA.",
  };

  it("rejects PRAX's 09-11 edit at submit, where the writer can fix it", () => {
    const parsed = thesisDecisionSchema.safeParse({ ...validLong, edit_triggers: [PRAX_0911_EDIT] });
    expect(parsed.success).toBe(false);
    expect(parsed.error?.issues[0]?.path).toEqual(["edit_triggers", 0, "action"]);
  });

  it("accepts a real action name", () => {
    const parsed = thesisDecisionSchema.safeParse({
      ...validLong,
      edit_triggers: [{ id: PRAX_0911_EDIT.id, action: "REVIEW", days: 7, rationale: "Weekly into the PDUFA." }],
    });
    expect(parsed.success).toBe(true);
  });

  it("is the one shared edit form, not a copy that can drift", () => {
    expect(thesisDecisionSchema.shape.edit_triggers.unwrap().element).toBe(editTriggerOpSchema);
  });
});
