/**
 * decision.test.ts — validateThesisDecision(), the V2 writer's in-loop
 * Layer-1 pre-validation. These rules are what turns a would-be persist
 * rejection into a one-step repair inside the research loop, so the
 * accept/reject boundary is pinned hard.
 */

import {
  validateThesisDecision,
  type ThesisDecisionInput,
} from "./decision";

const validLong: ThesisDecisionInput = {
  direction: "LONG",
  rationale: "Blackwell ramp is underpriced; entry at the breakout with a clean 2.5:1.",
  horizon: "TARGET",
  entry_price: 100,
  target_price: 125,
  stop_loss: 90,
  core_belief:
    "NVDA prints ≥$50B data-center revenue by Q4 FY26 as Blackwell replaces Hopper at hyperscalers.",
  key_assumptions: ["DC capex stays above $200B/yr", "Blackwell yields hold above 60%"],
  invalidation_conditions: ["Gross margin below 70% on next print", "Guidance cut on DC revenue"],
  scoring: {
    trendStrength: { score: 3, note: "multi-week uptrend, rising 50d" },
    relativeStrength: { score: 2, note: "+28% YTD vs AMD +14%" },
    entryQuality: { score: 2, note: "pullback to 20d in trend" },
    catalystFreshness: { score: 2, note: "earnings 3 weeks out, beat-raise setup" },
  },
  conviction: "HIGH",
  conviction_rationale:
    "I really like this setup — the catalyst is ahead and consensus is too conservative on DC revenue.",
  variant_view: "Consensus models $42B DC; channel checks support $50B+ — 2 quarters underweighted.",
  target_size_pct: 4,
};

const mintOpts = { mode: "mint" as const, existingStatus: null, currentPrice: 101 };

describe("validateThesisDecision — accept paths", () => {
  it("accepts a fully-specified LONG mint and computes composite + R/R", () => {
    const v = validateThesisDecision(validLong, mintOpts);
    expect(v.ok).toBe(true);
    expect(v.errors).toEqual([]);
    expect(v.decision?.composite).toBe(9);
    expect(v.riskReward).toBeCloseTo(2.5);
  });

  it("accepts a PASS with only rationale + horizon (no prices, no conviction)", () => {
    const v = validateThesisDecision(
      {
        direction: "PASS",
        rationale: "No 2:1 setup at current prices; revisit below the 50d around $85.",
        horizon: "TARGET",
      },
      mintOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("accepts a valid SHORT with mirrored price ordering", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        direction: "SHORT",
        entry_price: 100,
        target_price: 80,
        stop_loss: 108,
      },
      mintOpts,
    );
    expect(v.ok).toBe(true);
    expect(v.riskReward).toBeCloseTo(2.5);
  });

  it("accepts omitted triggers (horizon defaults apply downstream)", () => {
    const v = validateThesisDecision({ ...validLong, triggers: undefined }, mintOpts);
    expect(v.ok).toBe(true);
    expect(v.decision?.triggers).toBeUndefined();
  });

  it("accepts a well-formed WATCHING trigger ladder (ENTER + REVIEW)", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        triggers: [
          {
            predicate: { kind: "PRICE_ABOVE", level: 100 },
            action: "ENTER",
            rationale: "breakout entry",
          },
          {
            predicate: { kind: "EARNINGS_MISS", minSurprisePct: 3 },
            action: "REVIEW",
            rationale: "guidance miss kills the thesis",
          },
        ],
      },
      mintOpts,
    );
    expect(v.ok).toBe(true);
    expect(v.decision?.triggers).toHaveLength(2);
    // ids are auto-generated by the schema default
    expect(v.decision?.triggers?.[0].id).toBeTruthy();
  });
});

describe("validateThesisDecision — R/R floor and price ordering", () => {
  it("rejects a LONG below 2:1", () => {
    const v = validateThesisDecision(
      { ...validLong, target_price: 115, stop_loss: 90 }, // 15/10 = 1.5
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("R/R floor");
  });

  it("rejects inverted LONG ordering (stop above entry)", () => {
    const v = validateThesisDecision(
      { ...validLong, stop_loss: 105 },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("price ordering");
  });

  it("rejects a directional decision with missing prices", () => {
    const v = validateThesisDecision(
      { ...validLong, entry_price: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("entry_price");
  });
});

describe("validateThesisDecision — belief + conviction requirements (LONG/SHORT)", () => {
  it("rejects missing core_belief / thin assumptions / thin invalidations", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        core_belief: undefined,
        key_assumptions: ["only one"],
        invalidation_conditions: [],
      },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    const all = v.errors.join(" ");
    expect(all).toContain("core_belief");
    expect(all).toContain("key_assumptions");
    expect(all).toContain("invalidation_conditions");
  });

  it("rejects STRONG/HIGH conviction without a variant view", () => {
    const v = validateThesisDecision(
      { ...validLong, conviction: "STRONG", variant_view: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("variant_view");
  });

  it("allows MEDIUM conviction without a variant view", () => {
    const v = validateThesisDecision(
      { ...validLong, conviction: "MEDIUM", variant_view: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(true);
  });

  it("rejects missing scoring dimensions and out-of-cap scores", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        scoring: {
          trendStrength: { score: 5, note: "over cap" },
          relativeStrength: { score: 2, note: "ok" },
          entryQuality: { score: 2, note: "" },
          catalystFreshness: { score: 2, note: "ok" },
        },
      },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    const all = v.errors.join(" ");
    expect(all).toContain("scoring.trendStrength");
    expect(all).toContain("scoring.entryQuality");
  });
});

describe("validateThesisDecision — horizon conditionals", () => {
  it("CATALYST requires catalyst_date", () => {
    const v = validateThesisDecision(
      { ...validLong, horizon: "CATALYST", catalyst_date: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("catalyst_date");
  });

  it("TRADE requires max_hold_days", () => {
    const v = validateThesisDecision(
      { ...validLong, horizon: "TRADE", max_hold_days: undefined },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("max_hold_days");
  });

  it("rejects an unparseable catalyst_date", () => {
    const v = validateThesisDecision(
      { ...validLong, horizon: "CATALYST", catalyst_date: "next month sometime" },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("not a parseable date");
  });
});

describe("validateThesisDecision — trigger action-set by position state", () => {
  const enterTrigger = {
    predicate: { kind: "PRICE_ABOVE", level: 100 },
    action: "ENTER",
    rationale: "breakout",
  };
  const exitTrigger = {
    predicate: { kind: "PRICE_BELOW", level: 90 },
    action: "EXIT",
    rationale: "stop",
  };

  it("mint (no position): EXIT/TRIM/ADD/MOVE_STOP are forbidden", () => {
    const v = validateThesisDecision({ ...validLong, triggers: [exitTrigger] }, mintOpts);
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("no position exists");
  });

  it("HOLDING refresh: ENTER is forbidden", () => {
    const v = validateThesisDecision(
      { ...validLong, triggers: [enterTrigger] },
      { mode: "refresh", existingStatus: "HOLDING", currentPrice: 101 },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("ENTER triggers are forbidden");
  });

  it("HOLDING refresh: EXIT + REVIEW ladder is legal", () => {
    const v = validateThesisDecision(
      {
        ...validLong,
        triggers: [
          exitTrigger,
          {
            predicate: { kind: "REVIEW_DATE_HIT" },
            action: "REVIEW",
            rationale: "scheduled hygiene",
          },
        ],
      },
      { mode: "refresh", existingStatus: "HOLDING", currentPrice: 101 },
    );
    expect(v.ok).toBe(true);
  });

  it("PROMOTED refresh (no live position): EXIT is forbidden, ENTER is legal", () => {
    const promotedOpts = { mode: "refresh" as const, existingStatus: "PROMOTED", currentPrice: 101 };
    expect(
      validateThesisDecision({ ...validLong, triggers: [exitTrigger] }, promotedOpts).ok,
    ).toBe(false);
    expect(
      validateThesisDecision({ ...validLong, triggers: [enterTrigger] }, promotedOpts).ok,
    ).toBe(true);
  });

  it("malformed trigger shapes are reported as repairable errors, not thrown", () => {
    const v = validateThesisDecision(
      { ...validLong, triggers: [{ nonsense: true }] },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("triggers: invalid shape");
    expect(v.errors.join(" ")).toContain("OMIT the triggers field");
  });
});

describe("validateThesisDecision — persist-gate mirrors (review finding #4)", () => {
  it("rejects a PASS carrying triggers", () => {
    const v = validateThesisDecision(
      {
        direction: "PASS",
        rationale: "No edge at current prices; keep an eye on the reclaim level.",
        horizon: "TARGET",
        triggers: [
          { predicate: { kind: "PRICE_ABOVE", level: 100 }, action: "ENTER", rationale: "x" },
        ],
      },
      mintOpts,
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("PASS decision cannot carry triggers");
  });

  it("goalpost mirror: rejects a target raise on WATCHING when price already crossed the old target", () => {
    const v = validateThesisDecision(
      { ...validLong, target_price: 140 },
      {
        mode: "refresh",
        existingStatus: "WATCHING",
        currentPrice: 132,
        existingTargetPrice: 130,
        existingHasTriggers: true,
      },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("goalpost");
  });

  it("goalpost mirror: allows a target raise while price is still below the old target", () => {
    const v = validateThesisDecision(
      { ...validLong, target_price: 140, stop_loss: 84 },
      {
        mode: "refresh",
        existingStatus: "WATCHING",
        currentPrice: 101,
        existingTargetPrice: 130,
        existingHasTriggers: true,
      },
    );
    expect(v.ok).toBe(true);
  });

  it("zero-trigger mirror: a refresh on a bare thesis may not omit triggers", () => {
    const v = validateThesisDecision({ ...validLong, triggers: undefined }, {
      mode: "refresh",
      existingStatus: "WATCHING",
      currentPrice: 101,
      existingTargetPrice: 130,
      existingHasTriggers: false,
    });
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("NO triggers");
  });

  it("enter-guard mirror: WATCHING refresh with a REVIEW-only ladder is rejected...", () => {
    const reviewOnly = [
      { predicate: { kind: "REVIEW_DATE_HIT" }, action: "REVIEW", rationale: "hygiene" },
    ];
    const v = validateThesisDecision(
      { ...validLong, triggers: reviewOnly },
      { mode: "refresh", existingStatus: "WATCHING", currentPrice: 90, existingTargetPrice: 130, existingHasTriggers: true },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("ENTER rung");
  });

  it("...unless entry equals the live price (buy-at-market carve-out)", () => {
    const reviewOnly = [
      { predicate: { kind: "REVIEW_DATE_HIT" }, action: "REVIEW", rationale: "hygiene" },
    ];
    const v = validateThesisDecision(
      { ...validLong, triggers: reviewOnly },
      { mode: "refresh", existingStatus: "WATCHING", currentPrice: 100, existingTargetPrice: 130, existingHasTriggers: true },
    );
    expect(v.ok).toBe(true);
  });

  it("enter-guard mirror: HOLDING refresh ladder must carry an EXIT rung", () => {
    const noExit = [
      { predicate: { kind: "GAIN_FROM_ENTRY", pct: 10, direction: "UP" }, action: "ADD", rationale: "press" },
      { predicate: { kind: "REVIEW_DATE_HIT" }, action: "REVIEW", rationale: "hygiene" },
    ];
    const v = validateThesisDecision(
      { ...validLong, triggers: noExit },
      { mode: "refresh", existingStatus: "HOLDING", currentPrice: 110, existingTargetPrice: 130, existingHasTriggers: true },
    );
    expect(v.ok).toBe(false);
    expect(v.errors.join(" ")).toContain("EXIT rung");
  });
});
